---
title: "Bienvenue sur le projet Modèle hiérarchique bayésien pour l’écologie"
author: "NGUYEN Duc Hoang Viet  et  Tchanang Yvan Michel "
---

# Présentation du projet

On s’intéresse dans ce projet à la modélisation de la présence du moustique tigre (*Aedes albopictus*) en France métropolitaine.

Pour cela, on dispose de données d’occurences du moustique tigre, que l’on peut trouver par exemple sur le site de GBIF (Global Biodiversity Information Facility, https://www.gbif.org/).

Le but est d’analyser la variabilité inter-site et intra-site des occurrences, en utilisant un modèle hiérarchique bayésien.

Le projet est divisé en plusieurs parties :

-   **Partie 1 :** Extraction des données et pré-traitement

    Cette partie est dédiée à l'extraction des données au nettoyage des valeurs manquantes et à la visualisation initiale pour comprendre la distribution d' Aedes albopictus.

-   **Partie 2 :** Construction du modèle hiérarchique bayésien

    Nous avons expérimenté deux méthodes pour l'implémentation du modèle initial :

    ```         
        Méthode 1 : Génération par blocs séparés. Elle est dans la version 1. 

        Méthode 2 : Génération du vecteur θ dans son ensemble. Elle est contenue dans la version 2. Note importante : Pour assurer le bon fonctionnement de cette méthode, il est impératif que le fichier de code soit placé dans le même répertoire racine que le répertoire data, afin de permettre l'accès direct au fichier summary_tigre_moustique.csv.
    ```

-   **Partie 3 :** Modele extension

    Dans cette partie, nous avons adopté la même méthode que celle utilisée dans la version 1 puisqu'elle demande de modifier les paramètres de la première partie, la seconde approche, plus modulaire est la plus adaptée.

::: callout-note
## Consulter le rapport complet

Vous pouvez consulter le rapport détaillé du projet (format PDF) en cliquant sur le lien ci-dessous :

<a href="Rapport.pdf" target="_blank" style="font-weight: bold; text-decoration: underline;"> 📄 Ouvrir le rapport PDF </a>
:::
